// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaN8l4R-q8LGWjNtDFSnNxdcNeGO_Hclw',
    appId: '1:894253407427:web:e9ecc9e3a1ddb4cfb59676',
    messagingSenderId: '894253407427',
    projectId: 'eshop-app-5575b',
    authDomain: 'eshop-app-5575b.firebaseapp.com',
    storageBucket: 'eshop-app-5575b.firebasestorage.app',
    measurementId: 'G-81WVDDZ0J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5PUDiCtB3_6fYGBGdElOh6umDwpR6Os',
    appId: '1:894253407427:android:913cf6c66baf3c1cb59676',
    messagingSenderId: '894253407427',
    projectId: 'eshop-app-5575b',
    storageBucket: 'eshop-app-5575b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvFtf4UcpDBYjtB4WEBFitxIM1shc2Qs',
    appId: '1:894253407427:ios:c3b760dc65f55e0bb59676',
    messagingSenderId: '894253407427',
    projectId: 'eshop-app-5575b',
    storageBucket: 'eshop-app-5575b.firebasestorage.app',
    iosBundleId: 'com.example.eshopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvFtf4UcpDBYjtB4WEBFitxIM1shc2Qs',
    appId: '1:894253407427:ios:c3b760dc65f55e0bb59676',
    messagingSenderId: '894253407427',
    projectId: 'eshop-app-5575b',
    storageBucket: 'eshop-app-5575b.firebasestorage.app',
    iosBundleId: 'com.example.eshopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaN8l4R-q8LGWjNtDFSnNxdcNeGO_Hclw',
    appId: '1:894253407427:web:aae282e06fced03cb59676',
    messagingSenderId: '894253407427',
    projectId: 'eshop-app-5575b',
    authDomain: 'eshop-app-5575b.firebaseapp.com',
    storageBucket: 'eshop-app-5575b.firebasestorage.app',
    measurementId: 'G-9767ELBPV6',
  );
}
